// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: horoscopesnippet

package com.tencent.java.proto;

public final class HoroscopeSnippetProtos {
  private HoroscopeSnippetProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HoroscopeSnippetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.horoscopesnippet.HoroscopeSnippet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string extended_link = 7;</code>
     */
    boolean hasExtendedLink();
    /**
     * <code>optional string extended_link = 7;</code>
     */
    java.lang.String getExtendedLink();
    /**
     * <code>optional string extended_link = 7;</code>
     */
    com.google.protobuf.ByteString
        getExtendedLinkBytes();

    /**
     * <code>optional string author = 10;</code>
     */
    boolean hasAuthor();
    /**
     * <code>optional string author = 10;</code>
     */
    java.lang.String getAuthor();
    /**
     * <code>optional string author = 10;</code>
     */
    com.google.protobuf.ByteString
        getAuthorBytes();

    /**
     * <code>optional uint64 ts_update = 12;</code>
     */
    boolean hasTsUpdate();
    /**
     * <code>optional uint64 ts_update = 12;</code>
     */
    long getTsUpdate();
  }
  /**
   * Protobuf type {@code proto.horoscopesnippet.HoroscopeSnippet}
   */
  public static final class HoroscopeSnippet extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.horoscopesnippet.HoroscopeSnippet)
      HoroscopeSnippetOrBuilder {
    // Use HoroscopeSnippet.newBuilder() to construct.
    private HoroscopeSnippet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HoroscopeSnippet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HoroscopeSnippet defaultInstance;
    public static HoroscopeSnippet getDefaultInstance() {
      return defaultInstance;
    }

    public HoroscopeSnippet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HoroscopeSnippet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              extendedLink_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              author_ = bs;
              break;
            }
            case 96: {
              bitField0_ |= 0x00000004;
              tsUpdate_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.java.proto.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_HoroscopeSnippet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.java.proto.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_HoroscopeSnippet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet.class, com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet.Builder.class);
    }

    public static com.google.protobuf.Parser<HoroscopeSnippet> PARSER =
        new com.google.protobuf.AbstractParser<HoroscopeSnippet>() {
      public HoroscopeSnippet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HoroscopeSnippet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HoroscopeSnippet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int EXTENDED_LINK_FIELD_NUMBER = 7;
    private java.lang.Object extendedLink_;
    /**
     * <code>optional string extended_link = 7;</code>
     */
    public boolean hasExtendedLink() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string extended_link = 7;</code>
     */
    public java.lang.String getExtendedLink() {
      java.lang.Object ref = extendedLink_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          extendedLink_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string extended_link = 7;</code>
     */
    public com.google.protobuf.ByteString
        getExtendedLinkBytes() {
      java.lang.Object ref = extendedLink_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extendedLink_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHOR_FIELD_NUMBER = 10;
    private java.lang.Object author_;
    /**
     * <code>optional string author = 10;</code>
     */
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string author = 10;</code>
     */
    public java.lang.String getAuthor() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          author_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string author = 10;</code>
     */
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TS_UPDATE_FIELD_NUMBER = 12;
    private long tsUpdate_;
    /**
     * <code>optional uint64 ts_update = 12;</code>
     */
    public boolean hasTsUpdate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 ts_update = 12;</code>
     */
    public long getTsUpdate() {
      return tsUpdate_;
    }

    private void initFields() {
      extendedLink_ = "";
      author_ = "";
      tsUpdate_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(7, getExtendedLinkBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(10, getAuthorBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(12, tsUpdate_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getExtendedLinkBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getAuthorBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(12, tsUpdate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.horoscopesnippet.HoroscopeSnippet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.horoscopesnippet.HoroscopeSnippet)
        com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.java.proto.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_HoroscopeSnippet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.java.proto.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_HoroscopeSnippet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet.class, com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet.Builder.class);
      }

      // Construct using com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        extendedLink_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        author_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        tsUpdate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.java.proto.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_HoroscopeSnippet_descriptor;
      }

      public com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet getDefaultInstanceForType() {
        return com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet.getDefaultInstance();
      }

      public com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet build() {
        com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet buildPartial() {
        com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet result = new com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.extendedLink_ = extendedLink_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.author_ = author_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tsUpdate_ = tsUpdate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet) {
          return mergeFrom((com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet other) {
        if (other == com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet.getDefaultInstance()) return this;
        if (other.hasExtendedLink()) {
          bitField0_ |= 0x00000001;
          extendedLink_ = other.extendedLink_;
          onChanged();
        }
        if (other.hasAuthor()) {
          bitField0_ |= 0x00000002;
          author_ = other.author_;
          onChanged();
        }
        if (other.hasTsUpdate()) {
          setTsUpdate(other.getTsUpdate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.java.proto.HoroscopeSnippetProtos.HoroscopeSnippet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object extendedLink_ = "";
      /**
       * <code>optional string extended_link = 7;</code>
       */
      public boolean hasExtendedLink() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string extended_link = 7;</code>
       */
      public java.lang.String getExtendedLink() {
        java.lang.Object ref = extendedLink_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            extendedLink_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string extended_link = 7;</code>
       */
      public com.google.protobuf.ByteString
          getExtendedLinkBytes() {
        java.lang.Object ref = extendedLink_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extendedLink_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string extended_link = 7;</code>
       */
      public Builder setExtendedLink(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        extendedLink_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string extended_link = 7;</code>
       */
      public Builder clearExtendedLink() {
        bitField0_ = (bitField0_ & ~0x00000001);
        extendedLink_ = getDefaultInstance().getExtendedLink();
        onChanged();
        return this;
      }
      /**
       * <code>optional string extended_link = 7;</code>
       */
      public Builder setExtendedLinkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        extendedLink_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object author_ = "";
      /**
       * <code>optional string author = 10;</code>
       */
      public boolean hasAuthor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string author = 10;</code>
       */
      public java.lang.String getAuthor() {
        java.lang.Object ref = author_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            author_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string author = 10;</code>
       */
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        java.lang.Object ref = author_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          author_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string author = 10;</code>
       */
      public Builder setAuthor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        author_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string author = 10;</code>
       */
      public Builder clearAuthor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        author_ = getDefaultInstance().getAuthor();
        onChanged();
        return this;
      }
      /**
       * <code>optional string author = 10;</code>
       */
      public Builder setAuthorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        author_ = value;
        onChanged();
        return this;
      }

      private long tsUpdate_ ;
      /**
       * <code>optional uint64 ts_update = 12;</code>
       */
      public boolean hasTsUpdate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 ts_update = 12;</code>
       */
      public long getTsUpdate() {
        return tsUpdate_;
      }
      /**
       * <code>optional uint64 ts_update = 12;</code>
       */
      public Builder setTsUpdate(long value) {
        bitField0_ |= 0x00000004;
        tsUpdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 ts_update = 12;</code>
       */
      public Builder clearTsUpdate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tsUpdate_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.horoscopesnippet.HoroscopeSnippet)
    }

    static {
      defaultInstance = new HoroscopeSnippet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.horoscopesnippet.HoroscopeSnippet)
  }

  public interface SummaryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.horoscopesnippet.Summary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string text = 1;</code>
     */
    boolean hasText();
    /**
     * <code>required string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <code>required string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code proto.horoscopesnippet.Summary}
   */
  public static final class Summary extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.horoscopesnippet.Summary)
      SummaryOrBuilder {
    // Use Summary.newBuilder() to construct.
    private Summary(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Summary(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Summary defaultInstance;
    public static Summary getDefaultInstance() {
      return defaultInstance;
    }

    public Summary getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Summary(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              text_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.java.proto.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_Summary_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.java.proto.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_Summary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.java.proto.HoroscopeSnippetProtos.Summary.class, com.tencent.java.proto.HoroscopeSnippetProtos.Summary.Builder.class);
    }

    public static com.google.protobuf.Parser<Summary> PARSER =
        new com.google.protobuf.AbstractParser<Summary>() {
      public Summary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Summary(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Summary> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TEXT_FIELD_NUMBER = 1;
    private java.lang.Object text_;
    /**
     * <code>required string text = 1;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.tencent.java.proto.HoroscopeSnippetProtos.Summary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.Summary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.Summary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.Summary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.Summary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.Summary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.Summary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.Summary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.Summary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.tencent.java.proto.HoroscopeSnippetProtos.Summary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tencent.java.proto.HoroscopeSnippetProtos.Summary prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.horoscopesnippet.Summary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.horoscopesnippet.Summary)
        com.tencent.java.proto.HoroscopeSnippetProtos.SummaryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.java.proto.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_Summary_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.java.proto.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_Summary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.java.proto.HoroscopeSnippetProtos.Summary.class, com.tencent.java.proto.HoroscopeSnippetProtos.Summary.Builder.class);
      }

      // Construct using com.tencent.java.proto.HoroscopeSnippetProtos.Summary.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.java.proto.HoroscopeSnippetProtos.internal_static_proto_horoscopesnippet_Summary_descriptor;
      }

      public com.tencent.java.proto.HoroscopeSnippetProtos.Summary getDefaultInstanceForType() {
        return com.tencent.java.proto.HoroscopeSnippetProtos.Summary.getDefaultInstance();
      }

      public com.tencent.java.proto.HoroscopeSnippetProtos.Summary build() {
        com.tencent.java.proto.HoroscopeSnippetProtos.Summary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tencent.java.proto.HoroscopeSnippetProtos.Summary buildPartial() {
        com.tencent.java.proto.HoroscopeSnippetProtos.Summary result = new com.tencent.java.proto.HoroscopeSnippetProtos.Summary(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.java.proto.HoroscopeSnippetProtos.Summary) {
          return mergeFrom((com.tencent.java.proto.HoroscopeSnippetProtos.Summary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.java.proto.HoroscopeSnippetProtos.Summary other) {
        if (other == com.tencent.java.proto.HoroscopeSnippetProtos.Summary.getDefaultInstance()) return this;
        if (other.hasText()) {
          bitField0_ |= 0x00000001;
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasText()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.java.proto.HoroscopeSnippetProtos.Summary parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.java.proto.HoroscopeSnippetProtos.Summary) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <code>required string text = 1;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.horoscopesnippet.Summary)
    }

    static {
      defaultInstance = new Summary(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.horoscopesnippet.Summary)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_horoscopesnippet_HoroscopeSnippet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_horoscopesnippet_HoroscopeSnippet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_horoscopesnippet_Summary_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_horoscopesnippet_Summary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020horoscopesnippet\022\026proto.horoscopesnipp" +
      "et\"L\n\020HoroscopeSnippet\022\025\n\rextended_link\030" +
      "\007 \001(\t\022\016\n\006author\030\n \001(\t\022\021\n\tts_update\030\014 \001(\004" +
      "\"\027\n\007Summary\022\014\n\004text\030\001 \002(\tB0\n\026com.tencent" +
      ".java.protoB\026HoroscopeSnippetProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_horoscopesnippet_HoroscopeSnippet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_horoscopesnippet_HoroscopeSnippet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_horoscopesnippet_HoroscopeSnippet_descriptor,
        new java.lang.String[] { "ExtendedLink", "Author", "TsUpdate", });
    internal_static_proto_horoscopesnippet_Summary_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_horoscopesnippet_Summary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_horoscopesnippet_Summary_descriptor,
        new java.lang.String[] { "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
